services:
  mysql:
    image: mysql:8.0
    container_name: yanawa-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -uroot -p"$${MYSQL_ROOT_PASSWORD}"',
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: yanawa-api
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

    ports:
      - '127.0.0.1:5000:5000'
    #   127.0.0.1 : 5000 : 5000
    #       │         │      │
    #       │         │      └─ Flask 컨테이너 내부 포트
    #       │         └──────── EC2 Ubuntu의 포트
    #       └────────────────── EC2 자기 자신에서만 접근 허용

    volumes:
      - uploads_data:/app/uploads

volumes:
  mysql_data:
  uploads_data:
