services:
  mysql:
    image: mysql:8.0
    container_name: meeting-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meeting_db
      MYSQL_USER: meeting_user
      MYSQL_PASSWORD: meeting_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: